// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBda31RLy4d6pIp9CDU7oG3sDQu0JqDU_o',
    appId: '1:647653980311:web:9c5f431a0d85e9cc9391d2',
    messagingSenderId: '647653980311',
    projectId: 'decisionsapp-94fe9',
    authDomain: 'decisionsapp-94fe9.firebaseapp.com',
    storageBucket: 'decisionsapp-94fe9.appspot.com',
    measurementId: 'G-4W9PP9CCJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJZQmlyqSrtkqOK1vD8LEdivWb2JrXNXw',
    appId: '1:647653980311:android:1bc2dc8807add9a09391d2',
    messagingSenderId: '647653980311',
    projectId: 'decisionsapp-94fe9',
    storageBucket: 'decisionsapp-94fe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArYeDj4KcQnbZlxFSaYo7lGbo3shCCmQQ',
    appId: '1:647653980311:ios:0a4a12dff66d2b4a9391d2',
    messagingSenderId: '647653980311',
    projectId: 'decisionsapp-94fe9',
    storageBucket: 'decisionsapp-94fe9.appspot.com',
    iosClientId: '647653980311-83hq7kjvh12kb3oscu5ka7s14kt4vr51.apps.googleusercontent.com',
    iosBundleId: 'com.example.decisionsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArYeDj4KcQnbZlxFSaYo7lGbo3shCCmQQ',
    appId: '1:647653980311:ios:0a4a12dff66d2b4a9391d2',
    messagingSenderId: '647653980311',
    projectId: 'decisionsapp-94fe9',
    storageBucket: 'decisionsapp-94fe9.appspot.com',
    iosClientId: '647653980311-83hq7kjvh12kb3oscu5ka7s14kt4vr51.apps.googleusercontent.com',
    iosBundleId: 'com.example.decisionsapp',
  );
}
